name: Build for macos

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Build for macos
    runs-on: macos-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install ninja

      - name: Build Rust Compiler
        run: |
          ./configure --experimental-targets=Xtensa
          ./x.py build --stage 2
