name: Build for macos

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Build for macos
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: brew install ninja xz

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-submodules
        with:
          path: |
            ./src/tools/rust-installer
            ./src/doc/nomicon
            ./src/tools/cargo
            ./src/doc/reference
            ./src/doc/book
            ./src/tools/rls
            ./src/tools/rustfmt
            ./src/tools/miri
            ./src/doc/rust-by-example
            ./library/stdarch
            ./src/doc/rustc-dev-guide
            ./src/doc/edition-guide
            ./src/llvm-project
            ./src/doc/embedded-book
            ./src/tools/rust-analyzer
            ./library/backtrace
            ./build
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Reset git repo in case cache overwrote files
        run: git reset --hard

      - name: Update submodule ./src/tools/rust-installer
        run: git submodule update --init ./src/tools/rust-installer

      - name: Update submodule ./src/doc/nomicon
        run: git submodule update --init ./src/doc/nomicon

      - name: Update submodule ./src/tools/cargo
        run: git submodule update --init ./src/tools/cargo

      - name: Update submodule ./src/doc/reference
        run: git submodule update --init ./src/doc/reference

      - name: Update submodule ./src/doc/book
        run: git submodule update --init ./src/doc/book

      - name: Update submodule ./src/tools/rls
        run: git submodule update --init ./src/tools/rls

      - name: Update submodule ./src/tools/rustfmt
        run: git submodule update --init ./src/tools/rustfmt

      - name: Update submodule ./src/tools/miri
        run: git submodule update --init ./src/tools/miri

      - name: Update submodule ./src/doc/rust-by-example
        run: git submodule update --init ./src/doc/rust-by-example

      - name: Update submodule ./library/stdarch
        run: git submodule update --init ./library/stdarch

      - name: Update submodule ./src/doc/rustc-dev-guide
        run: git submodule update --init ./src/doc/rustc-dev-guide

      - name: Update submodule ./src/doc/edition-guide
        run: git submodule update --init ./src/doc/edition-guide

      - name: Update submodule ./src/llvm-project
        run: git submodule update --init ./src/llvm-project

      - name: Update submodule ./src/doc/embedded-book
        run: git submodule update --init ./src/doc/embedded-book

      - name: Update submodule ./src/tools/rust-analyzer
        run: git submodule update --init ./src/tools/rust-analyzer

      - name: Update submodule ./library/backtrace
        run: git submodule update --init ./library/backtrace

      - name: Update all submodules (just in case we have new submodules)
        run: git submodule update --init

      - name: Configure Build
        run: ./configure --experimental-targets=Xtensa

      - name: Build Rust Compiler
        run: ./x.py build --stage 2

      - name: Package files
        run: tar -c --lzma -v -f dist.tar.lzma --exclude .git src/ build/x86_64-apple-darwin

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tar.lzma
